# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool: Default

resources:
- repo: self

variables:
  tag: 'aianta/autowise'

stages:
- stage: Build_Deploy
  displayName: Build and Deploy

  jobs:
  - job: Build
    displayName: Build and Deploy
    steps:
    - task: Bash@3
      displayName: Build AutoWiSE Image
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          sudo docker build . -t $(tag)
          echo 'AutoWiSE image built!'


    - task: Bash@3
      displayName: Stopping any existing containers
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          sudo docker stop autowise
          echo 'AutoWiSE deployed!'

    - task: Bash@3
      displayName: Starting docker container
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          sudo docker run -p 8001:8001 -p 8002:8002 -v /home/aianta/autowise/conf/:/home/autowise/conf -v /home/aianta/autowise/data/:/home/autowise/data -d --rm --name autowise $(tag)
          echo 'AutoWiSE deployed!'
        failOnStderr: true